[package]
name = "rust-blueprint-api"
version = "0.1.0"
authors = ["Luis Dvlpr <luis.dvlpr@gmail.com>"]
edition = "2018"

[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/main.rs"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
env_logger = "0.7"